### ISSUE TITLE
two files with the same file name are in the repo

### ISSUE THREAD

**Issue by pgundlach** [Josef-Friedrich/LuaTeX_Lua-API#2]
In the directory LuaTeX_Lua-API/tree/main/examples/md5/ there are two files

```
git ls-tree HEAD .
[...]
100644 blob d2f92fec99f45e7c7508c1a90cde746d20ee2f00	sumHEXA.tex
100644 blob 99fd9b974914eacd728b9547489295072023d468	sumhexa.tex
```

which have the same file name in a case insensitive file system (like the default macOS AFS). Therefore the git is always "dirty" even after a fresh checkout.

Not a bug per se, but a minor nuisance.

**Comment by Josef-Friedrich** [comment]
Thank you for reporting this!
